name: fast_ui_kit
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  animate_do: ^3.0.2
  file_picker: ^5.3.1
  flutter:
    sdk: flutter
  horizontal_data_table: ^4.2.0
  mask: ^1.0.5
  skeletons: ^0.0.3
  zod_validation: ^1.0.1
  audioplayers: ^4.1.0
  scrollable_clean_calendar: ^1.4.1
  uuid: ^3.0.7
  # audio_in_app: ^1.0.1
# dependency_overrides:
#   # audioplayers: ^4.0.1
#   # file_picker: ^5.3.2
#   win32: ^5.0.2
#   path_provider_windows: ^2.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Ionicons
      fonts:
        - asset: assets/icons/Ionicons.ttf
    - family: AntDesign
      fonts:
        - asset: assets/icons/AntDesign.ttf
    - family: FontAwesome
      fonts:
        - asset: assets/icons/FontAwesome.ttf
    - family: MaterialIcons
      fonts:
        - asset: assets/icons/MaterialIcons.ttf
    - family: Entypo
      fonts:
        - asset: assets/icons/Entypo.ttf
    - family: EvilIcons
      fonts:
        - asset: assets/icons/EvilIcons.ttf
    - family: Feather
      fonts:
        - asset: assets/icons/Feather.ttf
    - family: Foundation
      fonts:
        - asset: assets/icons/Foundation.ttf
    - family: MaterialCommunityIcons
      fonts:
        - asset: assets/icons/MaterialCommunityIcons.ttf
    - family: Octicons
      fonts:
        - asset: assets/icons/Octicons.ttf
    - family: SimpleLineIcons
      fonts:
        - asset: assets/icons/SimpleLineIcons.ttf
    - family: Zocial
      fonts:
        - asset: assets/icons/Zocial.ttf
    - family: FontAwesome5
      fonts:
        - asset: assets/icons/FontAwesome5_Regular.ttf
    - family: FontAwesome5_Brands
      fonts:
        - asset: assets/icons/FontAwesome5_Brands.ttf
    - family: FontAwesome5_Solid
      fonts:
        - asset: assets/icons/FontAwesome5_Solid.ttf
    - family: WeatherIcons
      fonts:
        - asset: assets/icons/weathericons.ttf
    - family: Brandico
      fonts:
        - asset: assets/icons/Brandico.ttf
    - family: Elusive
      fonts:
        - asset: assets/icons/Elusive.ttf
    - family: FontAwesome5Icon
      fonts:
        - asset: assets/icons/FontAwesome5.ttf
    - family: Fontelico
      fonts:
        - asset: assets/icons/Fontelico.ttf
    - family: LineariconsFree
      fonts:
        - asset: assets/icons/LineariconsFree.ttf
    - family: Linecons
      fonts:
        - asset: assets/icons/Linecons.ttf
    - family: Maki
      fonts:
        - asset: assets/icons/Maki.ttf
    - family: Meteocons
      fonts:
        - asset: assets/icons/Meteocons.ttf
    - family: MfgLabs
      fonts:
        - asset: assets/icons/MfgLabs.ttf
    - family: ModernPictograms
      fonts:
        - asset: assets/icons/ModernPictograms.ttf
    - family: Typicons
      fonts:
        - asset: assets/icons/Typicons.ttf
    - family: WebSymbols
      fonts:
        - asset: assets/icons/WebSymbols.ttf
    - family: RpgAwesome
      fonts:
        - asset: assets/icons/RpgAwesome.ttf
