import 'package:fast_ui_kit/icons/icons_fonts/ant.dart';
import 'package:fast_ui_kit/icons/icons_fonts/brandico_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/elusive_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/entypo.dart';
import 'package:fast_ui_kit/icons/icons_fonts/evil_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/feather.dart';
import 'package:fast_ui_kit/icons/icons_fonts/font_awesome.dart';
import 'package:fast_ui_kit/icons/icons_fonts/font_awesome_5.dart';
import 'package:fast_ui_kit/icons/icons_fonts/font_awesome_5_brands.dart';
import 'package:fast_ui_kit/icons/icons_fonts/font_awesome_5_solid.dart';
import 'package:fast_ui_kit/icons/icons_fonts/font_elico_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/foundation.dart';
import 'package:fast_ui_kit/icons/icons_fonts/ionicons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/linecons_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/maki_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/material_community_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/material_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/meteocons_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/mfg_labs_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/modern_pictograms_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/octicons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/rpg_awesome_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/simple_line_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/typicons_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/weather_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/web_symbols_icons.dart';
import 'package:fast_ui_kit/icons/icons_fonts/zocial.dart';

class FastIcons {
  FastIcons._();

  static final ant = AntDesign();
  static final bradico = Brandico();
  static final elusive = Elusive();
  static final entypo = Entypo();
  static final evil = EvilIcons();
  static final feather = Feather();
  static final awesomeBrand5 = FontAwesome5Brands();
  static final awesomeSolid5 = FontAwesome5Solid();
  static final awesome5 = FontAwesome5();
  static final awesome = FontAwesome();
  static final elico = Fontelico();
  static final foundation = Foundation();
  static final ionicIcons = Ionicons();
  static final linear = AntDesign();
  static final line = Linecons();
  static final maki = Maki();
  static final mci = MaterialCommunityIcons();
  static final material = MaterialIcons();
  static final metocos = Meteocons();
  static final mfgLabs = MfgLabs();
  static final modernPictograms = ModernPictograms();
  static final ocIcons = Octicons();
  static final rpgAwesome = RpgAwesome();
  static final simpleLine = SimpleLineIcons();
  static final typIcons = Typicons();
  static final weather = WeatherIcons();
  static final web = WebSymbols();
  static final zocial = Zocial();
}
